name: Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Placeholder test step
        run: |
          echo "Tests placeholder - passing"
          exit 0 